version: "3.8"
services:
  banco:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - 5432:5432
volumes:
  postgres-data:
